# Generated by Django 2.1.3 on 2018-11-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='cinemas',
            new_name='cinema',
        ),
        migrations.RenameField(
            model_name='screening',
            old_name='movies',
            new_name='movie',
        ),
    ]
